name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller==5.13.0
        pip install opencv-python==4.7.0.72 numpy==1.23.5

    - name: Build EXE (关键步骤)
      run: |
        pyinstaller --onefile --noconsole ^
          --additional-hooks-dir=./hooks ^
          --hidden-import "numpy.core._multiarray_umath" ^
          --hidden-import "numpy.core._dtype_ctypes" ^
          iptv_tool.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IPTV-Tool
        path: dist/iptv_tool.exe
