name: Build EXE

on:
  workflow_dispatch:  # 只允许手动触发

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt5

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --windowed iptv_tool.py

    - name: Upload EXE file
      uses: actions/upload-artifact@v4  # 使用明确的版本v4
      with:
        name: iptv_tool
        path: dist/iptv_tool.exe
