name: Build IPTV Tool

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python-headless==4.7.0.72 requests==2.31.0 tqdm==4.66.1

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name IPTV_Tool ./iptv_tool.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: IPTV-Tool
        path: |
          dist/IPTV_Tool.exe
          rtp/*.txt
