name: Build Executable

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python requests tqdm opencc-python-reimplemented

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "rtp/*.txt;rtp" iptv_finder_gui.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: iptv-finder
        path: dist/
