name: iptvhost

on:
  # 定时触发（每12小时）
  schedule:
    - cron: '0 */12 * * *'
  # 手动触发配置（新增这个部分）
  workflow_dispatch:
    inputs:
      description:
        description: '手动触发说明（可选）'
        required: false
        default: '手动更新请求'
 
jobs:
  update_hosts:
    runs-on: ubuntu-latest
 
    steps:
    - name: Set DNS
      run: |
        echo "nameserver 223.5.5.5" | sudo tee /etc/resolv.conf > /dev/null
         
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 指定Python版本
 
    - name: Update DNS records and hosts file
      run: |
        set -x
        DNS_NAMES=(
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
        )
 
        HOSTS_MAPPING=(
          'cache.ott.ystenlive.itv.cmvideo.cn'
          'cache.ott.bestlive.itv.cmvideo.cn'
          'cache.ott.wasulive.itv.cmvideo.cn'
          'cache.ott.fifalive.itv.cmvideo.cn'
          'cache.ott.hnbblive.itv.cmvideo.cn'
        )
 
        > iptvhost.txt  # 确保文件名统一为iptvhost.txt
 
        for i in "${!DNS_NAMES[@]}"; do
          dns_name="${DNS_NAMES[$i]}"
          host="${HOSTS_MAPPING[$i]}"
          ip_address=$(dig +short "$dns_name" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          
          if [ -n "$ip_address" ]; then
            echo "$ip_address $host" >> iptvhost.txt
          fi
        done
 
    # 新增步骤：更新itv.m3u的hosts部分
    - name: Update M3U hosts configuration
      run: |
        python -c '
 import json
 
# 处理iptvhost.txt
hosts = []
with open("iptvhost.txt") as f:
    for line in f:
        line = line.strip()
        if line:
            ip, domain = line.split(" ", 1)
            hosts.append(f"{domain}={ip}")
 
# 更新m3u文件
with open("itv.m3u", "r+", encoding="utf-8") as f:
    data = json.load(f)
    data["hosts"] = hosts
    f.seek(0)
    json.dump(data, f, indent=4, ensure_ascii=False)
    f.truncate()
        '
 
    - name: Stage changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add iptvhost.txt itv.m3u  # 同时提交两个文件的修改
        git status
 
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update iptvhost and m3u configuration"
        branch: main
