name: iptvhost

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update_hosts:
    runs-on: ubuntu-latest

    steps:
    - name: Set DNS
      run: |
        echo "nameserver 223.5.5.5" | sudo tee /etc/resolv.conf > /dev/null

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Update DNS records
      run: |
        set -ex
        DNS_NAMES=(
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
          'base-v4v6-cm-miguvideo.e.cdn.chinamobile.com'
        )
        HOSTS_MAPPING=(
          'cache.ott.ystenlive.itv.cmvideo.cn'
          'cache.ott.bestlive.itv.cmvideo.cn'
          'cache.ott.wasulive.itv.cmvideo.cn'
          'cache.ott.fifalive.itv.cmvideo.cn'
          'cache.ott.hnbblive.itv.cmvideo.cn'
        )
        > iptvhost.txt
        for i in "${!DNS_NAMES[@]}"; do
          dns_name="${DNS_NAMES[$i]}"
          host="${HOSTS_MAPPING[$i]}"
          echo "正在解析: $dns_name"
          ip_address=$(dig +short "$dns_name" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          if [ -n "$ip_address" ]; then
            echo "$ip_address $host" >> iptvhost.txt
            echo "已更新: $ip_address -> $host"
          else
            echo "解析失败: $dns_name"
          fi
        done

    # 修正后的Python代码块
    - name: Update M3U configuration
      run: |
        python -c '
import json

# 读取生成的host文件
hosts = []
with open("iptvhost.txt") as f:
    for line in f:
        line = line.strip()
        if line:
            try:
                ip, domain = line.split(" ", 1)
                hosts.append(f"{domain}={ip}")
            except ValueError as e:
                print(f"格式错误跳过: {line}")

# 更新m3u文件
with open("itv.m3u", "r+", encoding="utf-8") as f:
    data = json.load(f)
    data["hosts"] = hosts
    f.seek(0)
    json.dump(data, f, indent=4, ensure_ascii=False)
    f.truncate()
        '

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "自动更新DNS映射配置"
        branch: main
        file_pattern: |
          iptvhost.txt
          itv.m3u
